- build.sbt
- src/main/scala/no/ndla/audioapi/AudioApiProperties.scala
Avhengig av ack og release av network
> #174: Tatt ibruk fellesfunksjonalitet for Domain

- build.sbt
- src/main/scala/no/ndla/audioapi/integration/MigrationApiClient.scala
Henger sammen med https://github.com/NDLANO/article-api/pull/89
> #86 update network lib 0.21

- src/main/scala/no/ndla/audioapi/auth/User.scala
- src/main/scala/no/ndla/audioapi/controller/AudioController.scala
- src/main/scala/no/ndla/audioapi/controller/InternController.scala
- src/main/scala/no/ndla/audioapi/service/ConverterService.scala
- src/main/scala/no/ndla/audioapi/service/ImportService.scala
- src/main/scala/no/ndla/audioapi/service/WriteService.scala
- src/test/scala/no/ndla/audioapi/service/WriteServiceTest.scala
Merger den til den andre pull requesten, så slipper du å reviewe de tingene flere ganger :)
> #761: Support for getting ndlaId or clientId from token

- build.sbt
resolves https://github.com/NDLANO/Issues/issues/948
> #948: Upgraded dependency for security reasons

- src/main/scala/no/ndla/audioapi/integration/Elastic4sClient.scala
connects to https://github.com/NDLANO/Issues/issues/1177
> #1177: Sets longer timeout for elastic4s client

- build.sbt
- src/main/scala/no/ndla/audioapi/AudioApiProperties.scala
- src/main/scala/no/ndla/audioapi/JettyLauncher.scala
> Added javamelody to component

- src/main/scala/db/migration/V5__AddAgreementToAudio.scala
- src/main/scala/db/migration/V6__TranslateUntranslatedAuthors.scala
- src/main/scala/no/ndla/audioapi/AudioApiProperties.scala
- src/main/scala/no/ndla/audioapi/service/ImportService.scala
- src/main/scala/no/ndla/audioapi/service/ValidationService.scala
- src/test/scala/no/ndla/audioapi/service/ImportServiceTest.scala
connects to NDLANO/Issues#499
Also refactors `ImportService` with separating persisting and converting the meta data.
> #499: Only import tags for relevant languages

- .travis.yml
- build.sbt
- project/assembly.sbt
- project/build.properties
- project/plugins.sbt
- src/main/scala/db/migration/V2__AddUpdatedColoums.scala
- src/main/scala/db/migration/V4__AddLanguageToAll.scala
- src/main/scala/db/migration/V5__AddAgreementToAudio.scala
- src/main/scala/db/migration/V6__TranslateUntranslatedAuthors.scala
- src/main/scala/db/migration/V7__UpdateLicenses.scala
- src/main/scala/no/ndla/audioapi/ComponentRegistry.scala
- src/main/scala/no/ndla/audioapi/DBMigrator.scala
- src/main/scala/no/ndla/audioapi/controller/AudioController.scala
- src/main/scala/no/ndla/audioapi/controller/HealthController.scala
- src/main/scala/no/ndla/audioapi/integration/DataSource.scala
- src/main/scala/no/ndla/audioapi/integration/Elastic4sClient.scala
- src/main/scala/no/ndla/audioapi/integration/MigrationApiClient.scala
- src/main/scala/no/ndla/audioapi/service/ImportService.scala
- src/main/scala/no/ndla/audioapi/service/search/IndexService.scala
- src/main/scala/no/ndla/audioapi/service/search/SearchConverterService.scala
- src/main/scala/no/ndla/audioapi/service/search/SearchService.scala
- src/test/scala/no/ndla/audioapi/TestEnvironment.scala
- src/test/scala/no/ndla/audioapi/controller/AudioControllerTest.scala
- src/test/scala/no/ndla/audioapi/controller/InternControllerTest.scala
- src/test/scala/no/ndla/audioapi/service/AudioStorageServiceTest.scala
- src/test/scala/no/ndla/audioapi/service/ImportServiceTest.scala
- src/test/scala/no/ndla/audioapi/service/WriteServiceTest.scala
- src/test/scala/no/ndla/audioapi/service/search/SearchConverterServiceTest.scala
- src/test/scala/no/ndla/audioapi/service/search/SearchServiceTest.scala
depends on https://github.com/NDLANO/network/pull/36
> Maintenance: Upgrades dependencies

- build.sbt
- src/main/scala/no/ndla/audioapi/AudioApiProperties.scala
connected to NDLANO/Issues#1439
> update network library version #1439

- src/main/scala/no/ndla/audioapi/AudioApiProperties.scala
- src/main/scala/no/ndla/audioapi/controller/AudioController.scala
- src/main/scala/no/ndla/audioapi/controller/NdlaController.scala
- src/main/scala/no/ndla/audioapi/model/api/Error.scala
- src/main/scala/no/ndla/audioapi/model/api/SearchResult.scala
- src/main/scala/no/ndla/audioapi/model/domain/SearchResult.scala
- src/main/scala/no/ndla/audioapi/service/search/SearchConverterService.scala
- src/main/scala/no/ndla/audioapi/service/search/SearchService.scala
- src/test/scala/no/ndla/audioapi/controller/AudioControllerTest.scala
- src/test/scala/no/ndla/audioapi/service/search/SearchServiceTest.scala
connects to NDLANO/Issues#1489
> #1489: Implements scrolling for audio-search

- src/main/scala/no/ndla/audioapi/AudioSwagger.scala
- src/main/scala/no/ndla/audioapi/controller/AudioController.scala
> Removed oauth from get and refreshed docs.

- src/main/scala/no/ndla/audioapi/AudioApiProperties.scala
- src/main/scala/no/ndla/audioapi/service/AudioStorageService.scala
- src/main/scala/no/ndla/audioapi/service/ImportService.scala
- src/test/scala/no/ndla/audioapi/UnitSuite.scala
- src/test/scala/no/ndla/audioapi/service/ImportServiceTest.scala
connects to NDLANO/Issues#1524
depends on https://github.com/NDLANO/migration-api/pull/1
> #1524: Adds basic auth to red.ndla.no requests

- src/main/scala/no/ndla/audioapi/AudioApiProperties.scala
- src/main/scala/no/ndla/audioapi/ComponentRegistry.scala
connects to NDLANO/Issues#1575
> #1575: Use correct s3 name and automatically detect s3 region

- .travis.yml
- release.sh
Virker ikke som `fast_finish` fungerer på den måten jeg ville, men tenker at siden release kun skjer på push til master, så er det ikke så fryktelig farlig om det tar litt tid (Bygget vil fremdeles gå grønt om release feiler).
> #1586: Update travis.yml to add release step

- src/main/scala/no/ndla/audioapi/controller/InternController.scala
- src/main/scala/no/ndla/audioapi/controller/NdlaController.scala
- src/main/scala/no/ndla/audioapi/model/api/AudioMetaDomainDump.scala
- src/main/scala/no/ndla/audioapi/model/domain/AudioMetaInformation.scala
- src/main/scala/no/ndla/audioapi/repository/AudioRepository.scala
- src/main/scala/no/ndla/audioapi/service/ReadService.scala
Partly fixes NDLANO/Issues#2105
> #2105: Adds domain dump endpoints to intern controller

- src/main/scala/no/ndla/audioapi/AudioApiProperties.scala
- src/main/scala/no/ndla/audioapi/controller/AudioController.scala
- src/main/scala/no/ndla/audioapi/model/Language.scala
- src/main/scala/no/ndla/audioapi/model/api/AudioMetaInformation.scala
- src/main/scala/no/ndla/audioapi/model/api/NewAudioMetaInformation.scala
- src/main/scala/no/ndla/audioapi/model/api/NewPodcastMeta.scala
- src/main/scala/no/ndla/audioapi/model/api/PodcastMeta.scala
- src/main/scala/no/ndla/audioapi/model/api/SearchParams.scala
- src/main/scala/no/ndla/audioapi/model/api/UpdatedAudioMetaInformation.scala
- src/main/scala/no/ndla/audioapi/model/domain/AudioMetaInformation.scala
- src/main/scala/no/ndla/audioapi/model/domain/PodcastMeta.scala
- src/main/scala/no/ndla/audioapi/model/domain/SearchSettings.scala
- src/main/scala/no/ndla/audioapi/model/search/SearchableAudioInformation.scala
- src/main/scala/no/ndla/audioapi/service/ConverterService.scala
- src/main/scala/no/ndla/audioapi/service/ImportService.scala
- src/main/scala/no/ndla/audioapi/service/ValidationService.scala
- src/main/scala/no/ndla/audioapi/service/search/IndexService.scala
- src/main/scala/no/ndla/audioapi/service/search/SearchConverterService.scala
- src/main/scala/no/ndla/audioapi/service/search/SearchService.scala
- src/test/scala/no/ndla/audioapi/controller/AudioControllerTest.scala
- src/test/scala/no/ndla/audioapi/controller/HealthControllerTest.scala
- src/test/scala/no/ndla/audioapi/controller/InternControllerTest.scala
- src/test/scala/no/ndla/audioapi/service/ConverterServiceTest.scala
- src/test/scala/no/ndla/audioapi/service/WriteServiceTest.scala
- src/test/scala/no/ndla/audioapi/service/search/SearchConverterServiceTest.scala
- src/test/scala/no/ndla/audioapi/service/search/SearchServiceTest.scala
Fixes NDLANO/Issues#2384
Legger til felter for podcast metadata.
Feltene kan kun spesifiseres dersom typen er 'podcast'
> #2384: Adds podcast metadata fields

- src/main/scala/no/ndla/audioapi/AudioApiProperties.scala
- src/main/scala/no/ndla/audioapi/model/api/AudioSummary.scala
- src/main/scala/no/ndla/audioapi/service/search/AudioIndexService.scala
- src/main/scala/no/ndla/audioapi/service/search/AudioSearchService.scala
- src/main/scala/no/ndla/audioapi/service/search/IndexService.scala
- src/main/scala/no/ndla/audioapi/service/search/TagIndexService.scala
- src/test/scala/no/ndla/audioapi/service/search/AudioSearchServiceTest.scala
- src/test/scala/no/ndla/audioapi/service/search/SearchConverterServiceTest.scala
Returnerer audioType som verdi i audio-søk.
> Returning audiotype in search

- src/main/scala/no/ndla/audioapi/model/api/AudioMetaInformation.scala
- src/main/scala/no/ndla/audioapi/service/ConverterService.scala
- src/main/scala/no/ndla/audioapi/service/ValidationService.scala
- src/test/scala/no/ndla/audioapi/controller/AudioControllerTest.scala
- src/test/scala/no/ndla/audioapi/controller/InternControllerTest.scala
- src/test/scala/no/ndla/audioapi/service/ConverterServiceTest.scala
Legger til datoer så vi kan bruke `<pubDate>` tag'en i podcast RSS'en i frontend
> Adds returning stored dates from endpoints

- src/main/scala/no/ndla/audioapi/model/api/AudioMetaInformation.scala
- src/main/scala/no/ndla/audioapi/model/api/NewAudioMetaInformation.scala
- src/main/scala/no/ndla/audioapi/model/api/UpdatedAudioMetaInformation.scala
- src/main/scala/no/ndla/audioapi/model/domain/AudioMetaInformation.scala
- src/main/scala/no/ndla/audioapi/service/ConverterService.scala
- src/main/scala/no/ndla/audioapi/service/ValidationService.scala
- src/main/scala/no/ndla/audioapi/service/WriteService.scala
- src/test/scala/no/ndla/audioapi/controller/AudioControllerTest.scala
- src/test/scala/no/ndla/audioapi/controller/InternControllerTest.scala
- src/test/scala/no/ndla/audioapi/service/ConverterServiceTest.scala
- src/test/scala/no/ndla/audioapi/service/WriteServiceTest.scala
Fixes https://github.com/NDLANO/Issues/issues/2629
Lagt til seriesId som nytt felt på ny og oppdatert episode.
> tilknytning-serie-fra-podkast

- .github/workflows/release.yml
- build.sbt
- build.sh
- project/assembly.sbt
Legger til blackbox, og gpg-nøkkel i release-workflow'en for å kunne release med den nye versjonen av deploy med krypterte hemmeligheter.
Testes ved å merge til master :woozy_face:
> Install blackbox and gpg key when releasing

- src/main/scala/no/ndla/audioapi/service/WriteService.scala
Sletter kun filer ved lagring av lyd dersom du sender inn ny fil.
> Fix deleting of file
